version: "2"
linters:
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - exhaustive
    - exhaustruct
    - goconst
    - gocritic
    - gosec
    - nilnil
    - revive
    - whitespace
